import React from 'react'
import { Container, Card, CardContent, Typography, Stack } from "@mui/material"
import { Link } from "react-router-dom"


const Privcypolicy = () => {
    return (
        <div style={ { minHeight: "100vh", padding: "2rem 0" } }>
            <Container maxWidth="lg">
                <Card style={ { minHeight: "100vh", boxShadow: "rgba(0, 0, 0, 0.1) 0px 14px 28px, rgba(0, 0, 0, 0.22) 0px 10px 10px" } }>
                    <Typography pt={ 2 } variant="h4" sx={ { textAlign: "center", fontWeight: "600", textTransform: "capitalize", letterSpacing: "1px" } }>Privacy Policy</Typography>
                    <CardContent sx={ {
                        padding: "2rem"
                    } }>
                        < Stack >
                            <Typography sx={ { color: "#063970", textTransform: "capitalize", letterSpacing: "0.7px", fontWeight: "bold" } }>This Privacy Policy is published in compliance of:</Typography>
                            <li style={ { listStyle: "none" } }>(i) Section 43A of 'The Information Technology Act, 2000';</li>
                            <li style={ { listStyle: "none" } }>(ii) Rule 4 of 'The Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Information) Rules, 2011' (hereinafter referred to as the "SPI Rules");</li>
                            <li style={ { listStyle: "none" } }>(iii) Relevant Provisions of 'The Consumer Protection Act, 2019' read with 'The Consumer Protection (E-Commerce) Rules, 2020'</li>
                        </Stack>
                        <Stack>
                            <Typography py={ 2 } sx={ { textTransform: "uppercase", fontWeight: "bolder" } }>1.defination</Typography>
                            <li style={ { listStyle: "none" } }>[User(s) are requested to refer/rely upon the definition clause incorporated in the another document named as 'Terms of Use' available in our Website(s)/Mobile Application(s) of PARTH in reference to all or any terms which are not defined hereinafter]</li>
                            <li style={ { listStyle: "none" } }>(i) "User ID": It is an identification code which is assigned with a unique, random number as a user identification to each individual User(s) through its computer/mobile devices by way of using "cookies", or similar other electronic tools in order to improve the responsiveness for our User(s) and their individual interests may be identified.</li>
                        </Stack>
                        <Stack>
                            <Typography py={ 2 } sx={ { textTransform: "uppercase", fontWeight: "bolder" } }>2.introduction</Typography>
                            <li style={ { listStyle: "none" } }>Parthtech Developers LLP ("Company" or "Parthtech" or "PARTH" or "We") is committed to serve you in most efficient manner. However, while serving you all, we ensure to consider your privacy utmost important and keep the same fully protected and safe. In order to ensure that We deliver our commitment, keep transparent processes to deal with and about the data we collect from our User(s) and how it is used and, we further ensure that it is never shared with any third parties with or without our conscious efforts.</li>
                            <li style={ { listStyle: "none" } }>This Privacy Policy shall apply to all our User(s) who visit and access our Website(s)/Mobile Application(s) developed by PARTH. User(s) herein unconditionally agree that browsing our Website(s)/Mobile Application(s) of PARTH and/or using its services signifies their unconditional assent to this Privacy Policy and the Terms of Use published herein.</li>
                            <li style={ { listStyle: "none" } }>We respect the privacy of our User(s) and, committed to protect it in all respects. Any dispute with Parthtech over any privacy matters are subject to this Privacy Policy read in conjunction with the 'Terms of Use' published on our Website(s)/Mobile Application(s) of PARTH.</li>
                            <li style={ { listStyle: "none" } }>By accessing and/or using the Website(s)/Mobile Application(s), the Users signify their agreement to accept this Privacy Policy. IF YOU DO NOT AGREE WITH ANY OR ALL OF THE FOLLOWING TERMS OF THE PRIVACY POLICY, PLEASE DO NOT ACCESS AND/OR USE THE WEBSITE(S)/MOBILE APPLICATION(S) OF PARTH.</li>
                        </Stack>
                        <Stack>
                            <Typography py={ 2 } sx={ { textTransform: "uppercase", fontWeight: "bolder" } }>3.personal information</Typography>
                            <li style={ { listStyle: "none" } }>"Personal Information" is defined under the SPI Rules to mean any information that relates to a natural person, which, either directly or indirectly, in combination with other information available or likely to be available with a body corporate, is capable of identifying such person.</li>
                            <li style={ { listStyle: "none" } }>The SPI Rules further define "sensitive personal data or information" (hereinafter referred to as the "SPDI") of a person to mean Personal Information about that person relating to: </li>
                            <li style={ { listStyle: "none" } }>(i) passwords; </li>
                            <li style={ { listStyle: "none" } }>(ii) financial information such as bank accounts, credit and debit card details or other payment instrument details;</li>
                            <li style={ { listStyle: "none" } }>(iii) physical, physiological and mental health condition;</li>
                            <li style={ { listStyle: "none" } }>(iv) name, age, address, e-mail, phone number, date of birth, sexual orientation;</li>
                            <li style={ { listStyle: "none" } }>(v) medical records and history;</li>
                            <li style={ { listStyle: "none" } }>(vi) biometric information;</li>
                            <li style={ { listStyle: "none" } }>(vii) information received by body corporate under lawful contract or otherwise;</li>
                            <li style={ { listStyle: "none" } }>(viii) visitor details as provided at the time of registration or thereafter; and</li>
                            <li style={ { listStyle: "none" } }>(ix) call data records.</li>
                            <li style={ { listStyle: "none" } }>All the aforementioned information is collectively referred to as "Personal Information." The information about the Users, as collected by us from the Website(s)/Mobile Application(s) of the PARTH, is given as below:</li>
                            <li style={ { listStyle: "none" } }>a) information supplied by the users and</li>
                            <li style={ { listStyle: "none" } }>b) information automatically tracked while navigation (Information).</li>
                            <li style={ { listStyle: "none" } }>By accessing/using our Website(s)/Mobile Application(s) of PARTH and/or its services by the User(s), he/she voluntarily and unconditionally gives his/her consent to collection, storage, and/or use of the Personal Information provided by him/her, including any other changes thereto as provided by him/her at any later stage, for availing any kind of the services that We offer.</li>
                            <li style={ { listStyle: "none" } }>To avail certain services on our Website(s)/Mobile Application(s) of PARTH, the User(s) may be required to provide certain information for the registration process that may include but not limited to :-</li>
                            <li style={ { listStyle: "none" } }>a) your name,</li>
                            <li style={ { listStyle: "none" } }>c) email address,</li>
                            <li style={ { listStyle: "none" } }>d) sex,</li>
                            <li style={ { listStyle: "none" } }>e) age,</li>
                            <li style={ { listStyle: "none" } }>f) credit card or debit card details,</li>
                            <li style={ { listStyle: "none" } }>g) medical records and history,</li>
                            <li style={ { listStyle: "none" } }>h) sexual orientation,</li>
                            <li style={ { listStyle: "none" } }>i) biometric information,</li>
                            <li style={ { listStyle: "none" } }>j) password etc., and/or your occupation, interests, and the like.</li>
                            <li style={ { listStyle: "none" } }>We presumes adequate and lawful parental consent in case the Personal Information is shared by any user under the age of 18 (eighteen) years.
                                The information as supplied by the User(s) enables us to improve our Website(s)/Mobile Application(s) of PARTH and provide back to the User(s) the most user-friendly experience.</li>
                            <li style={ { listStyle: "none" } }>All required information is service dependent and Parthtech may use the above said User(s) information to maintain, protect, and improve our services (including advertising services) and, also for developing and providing other new services for our User(s).</li>
                            <li style={ { listStyle: "none" } }>It is clarified that any information shall not be considered as sensitive in case it is freely available and accessible in the public domain or is furnished under the Right to Information Act, 2005 and any rules made thereunder or, any other law for the time being in force.</li>
                            <li style={ { listStyle: "none" } }>The primary reason for gathering information is to improve our products, deals, services, website content and navigation.</li>
                        </Stack>
                        <Stack>
                            <Typography py={ 2 } sx={ { textTransform: "uppercase", fontWeight: "bolder" } }>4.reasonable security practices as per the information technology act, 2000 and its rules
                            </Typography>
                            <li style={ { listStyle: "none" } }>We have implemented reasonable security practices as per Rule 8 of the SPI Rules as mentioned above and the Information Technology Act, 2000 amended through the Information Technology Amendment Act, 2008.</li>
                            <li style={ { listStyle: "none" } }>We have implemented stringent, internationally acceptable standards of technology, managerial security, technical security, operational security and physical security in order to protect your personally identifiable information from loss, misuse, disclosure, alteration or destruction. We have been assured by the third party cloud service providers (such as Google Cloud Services, Amazon Web Services and GoDaddy) that the data collected by us are managed and stored firmly and securely as per the globally accepted best practices.</li>
                            <li style={ { listStyle: "none" } }>We have implemented "Reasonable Security Practices" as required by the Information Technology Act, 2000 and the SPI Rules. By complying with such provisions, we assure our User(s) proper care and control over our I.T. and Security operations as required under relevant sections i.e. sections 43, 43A, 45, 66, 72A &amp; 85 of the Information Technology Act, 2000 read with the Information Technology Amendment Act, 2008 and including related rules made therein. However, Parthtech or its directors, shareholders, employees, and any other related persons (whether directly or indirectly) shall not be held responsible for any fraudulent/criminal activity in regard to misuse or unauthorized use of your sensitive personal information stored in our Website(s)/Mobile Application(s) of PARTH.</li>
                            <br />
                            <li style={ { listStyle: "none" } }>By accessing/using our Website(s)/Mobile Application(s) of PARTH, User(s) agree that We shall not be held responsible for any uncontrollable security attacks and any consequential losses (whether directly or indirectly) including financial losses, loss of opportunity, legal cost, attorney's fees, business losses, reputation loss, direct and indirect losses that may occur to the User(s), as per the statutory provisions of Section 43, 43A and 45 of the Information Technology Act, 2000 including any amendments in the said Act and any other laws of India for the time being in force.</li>
                            <li style={ { listStyle: "none" } }>You further agree that our management shall not be held responsible directly or indirectly for any cyber crime related criminal liabilities under the Information Technology Act, 2000/2008 relating to your information, as you have agreed and acknowledged that our management complies with due diligence (care &amp; controls) requirements of the Information Technology Act, 2000 including its rules and amendments.</li>
                            <li style={ { listStyle: "none" } }>We take appropriate security measures to protect against unauthorized access to or unauthorized alteration, disclosure or destruction of data. These include internal reviews of our data collection, storage and processing practices and security measures, including appropriate encryption and physical security measures to guard against unauthorized access to systems where we store personal data.</li>
                            <li style={ { listStyle: "none" } }>All information gathered on our Website(s)/Mobile Application(s) of PARTH is securely stored and managed by us on third party cloud service provider's server as mentioned earlier. However, as effective as our security measures are, no security system is impenetrable. We cannot guarantee the security of our database, nor can we guarantee that information you supply will not be intercepted while being transmitted to us over the internet. In any case, we take all reasonable efforts that any personal information provided by you to us is transmitted through modern cryptography (secure HTTPS connection).</li>
                            <li style={ { listStyle: "none" } }>User(s) agree that any information you include in a posting to the public discussion areas on our Website(s)/Mobile Application(s) of PARTH is available to anyone who has access to our Website(s)/Mobile Exchange(s) of PARTH.</li>
                            <li style={ { listStyle: "none" } }>However, the internet is an ever evolving medium. We may change our Privacy Policy from time to time to incorporate in lieu of necessary future changes and/or to comply with amendment in the existing laws, including but not limited to cover other technical upgradation (if any) that may come from time to time. Of course, our use of any information we gather will always be consistent with the policy under which the information was collected, regardless of what the new policy may be, provided that the same is not also contrary to the existing laws at the relevant time in future.</li>
                        </Stack>
                        <Stack>
                            <Typography py={ 2 } sx={ { textTransform: "uppercase", fontWeight: "bolder" } }>5. coockies</Typography>
                            <li style={ { listStyle: "none" } }>To improve the responsiveness for our User(s), we may use "cookies", or similar other electronic tools to collect information in order to assign each user a unique, random number as a user identification ("User ID") to understand each and every user&#39;s individual interests using their identified computer/mobile devices. Unless you voluntarily identify yourself` (through registration, for example), we will have no way of knowing who you are, even if we assign a cookie to your computer/mobile devices. A cookie also cannot read data off your hard drive. The Android and iOS applications do not use "cookies" explicitly. However, our Website(s)/Mobile Application(s) of PARTH may use third party code and libraries that use "cookies" to collect information and improve their services. User(s) have the option to either accept or refuse these cookies and, to know when a cookie is being sent to your device. However, in case the User(s) choose to refuse our cookies, he/she may not be able to use some/complete portions of our services.</li>
                            <li style={ { listStyle: "none" } }>Advertisers using the platform of our Website(s)/Mobile Application(s) of PARTH to advertise may also assign and use their own cookies to your browser, a process that we do not control.</li>
                            <li style={ { listStyle: "none" } }>Once the User(s) permit, We may obtain additional information such as list of apps installed on your device, device information, location, network carrier ("Information") available on your device, to personalize your experience and improve the app suggestions. This data may also be used at our end to take necessary business decisions.</li>
                            <li style={ { listStyle: "none" } }>We assure that all or any information of the User(s) shall not be shared with any third party and shall be purely utilized for enhancing each user experience and personalizing the services within PARTH networks.</li>
                            <li style={ { listStyle: "none" } }>Opting Out: In case any of the User(s) wish to opt out of storing cookies, the said user has an option to remove/block cookies in the corresponding internet browser's settings.</li>
                            <li style={ { listStyle: "none" } }>However, this may have a direct impact upon the corresponding User(s)'s experience of our services.
                                Log File Information: It is necessary to inform and clarify our User(s) that:</li>
                            <li style={ { listStyle: "none" } }>(i) We automatically collect limited information about your computer's or mobile's connection to the internet, mobile number/email address (if applicable), including your IP address, when you visit our Website(s)/Mobile Application(s) of PARTH.</li>
                            <li style={ { listStyle: "none" } }>(ii) Your IP address is a number that lets computers attached to the Internet know where to send you data – such as the pages you view.</li>
                            <li style={ { listStyle: "none" } }>(iii) We automatically receive and log information from your browser, including your IP address, your computer&#39;s name, your operating system, browser type and version.</li>
                        </Stack>
                        <Stack>
                            <Typography py={ 2 } sx={ { textTransform: "uppercase", fontWeight: "bolder" } }>6. information form other sources</Typography>
                            <li style={ { listStyle: "none" } }>(i) We may receive information about you from other sources, add it to our account information and treat it in accordance with this Privacy Policy.</li>
                            <li style={ { listStyle: "none" } }>(ii) If you provide information to the platform provider or other partner, whom we provide/receive services from, your account information and order information may be passed on to us.</li>
                            <li style={ { listStyle: "none" } }>(iii) We may obtain updated contact information from third parties in order to correct our records and fulfill the services or to communicate with you.</li>
                        </Stack>
                        <Stack>
                            <Typography py={ 2 } sx={ { textTransform: "uppercase", fontWeight: "bolder" } }>7. demographic and purchase information</Typography>
                            <li style={ { listStyle: "none" } }>(i) We may reference other sources of demographic and other information in order to provide you with more targeted communications and promotions. We use Google Analytics, among others, to track the User(s) behavior on our Website(s)/Mobile Application(s).</li>
                            <li style={ { listStyle: "none" } }>(ii) Google Analytics specifically has been enabled to support display advertising towards helping us to gain understanding of our User(s)&#39; Demographics and Interests.</li>
                            <li style={ { listStyle: "none" } }>(iii) The reports are anonymous and cannot be associated with any individual personally identifiable information that you may have shared with us.</li>
                        </Stack>
                        <Stack>
                            <Typography py={ 2 } sx={ { textTransform: "uppercase", fontWeight: "bolder" } }>8.link to third party sites/ad-servers</Typography>
                            <li style={ { listStyle: "none" } }>Our Website(s)/Mobile Application(s) of PARTH may also include links to other third party websites or mobile applications. Such websites or mobile applications are governed by their respective privacy policies, which are beyond our control.</li>
                            <li style={ { listStyle: "none" } }>Once the User(s) access any built-in third party service by switching to third party applications/websites [the User(s) can tell where you are by checking the URL in the location bar on your browser]. Use of any information the User(s) provide to such third party is governed by the respective privacy policy of the concerned operator of the said application/website, the User(s) are visiting. That policy may differ from ours. If the User(s) can&#39;t find the privacy policy of any of these third party websites/mobile applications including accessing their homepage, then the User(s) should contact the application or website owners directly for more information regarding this and/or for any other grievances.</li>
                            <li style={ { listStyle: "none" } }>When we present information to our advertisers – to help them understand our audience and confirm the value of advertising on our Website(s)/Mobile Application(s) of PARTH – it is usually in the form of aggregated statistics on traffic to various pages/content within our Website(s)/ Mobile Application(s) of PARTH.</li>
                            <li style={ { listStyle: "none" } }>We use third-party advertising companies to serve ads when the User(s) visit our Website(s)/Mobile Application(s) of PARTH. These companies may use information (not including your name, address, email address or telephone number or other personally identifiable sensitive/non-sensitive information) about your visits to this and other's websites or applications, in order to provide advertisements about goods and services of interest to the respective User(s).</li>
                            <li style={ { listStyle: "none" } }>We do not provide any Personal Information to any third party websites/advertisers/ad- servers without your consent, except in the circumstance mentioned in below clause.</li>
                        </Stack>
                        <Stack>
                            <Typography py={ 2 } sx={ { textTransform: "uppercase", fontWeight: "bolder" } }>9.information sharing</Typography>
                            <Typography sx={ { color: "#063970", textTransform: "capitalize", letterSpacing: "0.7px", fontWeight: "bold" } }>PARTH may share the sensitive Personal Information to any third party including Government Bodies / Government agencies / Government authorities / Service Provider / Alliance Partner without obtaining the prior consent of the User(s) in the following limited circumstances:</Typography>
                            <li style={ { listStyle: "none" } }>(i) When it is requested or required by law or by any court or governmental agency or authority to disclose, for the purpose of verification of identity, or for the prevention, detection, investigation including cyber incidents, or for prosecution and punishment of offences. These disclosures are made in good faith and belief that such disclosure is reasonably necessary for enforcing the Privacy Policy and Terms of Use and also, for the purpose of complying with the applicable laws and regulations during relevant time.</li>
                            <li style={ { listStyle: "none" } }>(ii) PARTH proposes to share such information within its group companies/affiliated companies and officers and employees of such group companies/affiliated companies for the purpose of processing Personal Information on its behalf. We also ensure that these recipients of such information agree to process such information based on our instructions and in compliance with this Privacy Policy and Terms of Use also published at our Website(s)/Mobile Application(s) of PARTH. The said group companies/affiliated companies also ensure that the Personal Information shared with them is not transferred to any third party, except as provided under this clause.</li>
                            <li style={ { listStyle: "none" } }>(iii) PARTH may use third-party advertising companies to serve ads when the User(s) visit our Website(s)/Mobile Application(s) of PARTH. These companies may use Personal Information (non-sensitive personal information only) about the User(s)&#39;s visit to our Website(s)/Mobile Application(s) of PARTH and other third party websites in order to provide advertisements about goods and services of interest to any particular User(s).</li>
                            <li style={ { listStyle: "none" } }>(iv) PARTH shall transfer information about the User(s) in case it is acquired by or merged with another company.</li>
                        </Stack>
                        <Stack>
                            <Typography py={ 2 } sx={ { textTransform: "uppercase", fontWeight: "bolder" } }>10.accessing, updating and deletion of personal information</Typography>
                            <Typography sx={ { color: "#063970", textTransform: "capitalize", letterSpacing: "0.7px", fontWeight: "bold" } }>When the User(s) use our Website(s)/Mobile Application(s) of PARTH:</Typography>
                            <li style={ { listStyle: "none" } }>(i) We make good faith efforts to provide our User(s), as and when requested by such User(s), with access to their Personal Information and shall further ensure that any Personal Information or sensitive personal data or information found to be inaccurate or deficient shall be corrected, modified or amended as feasible, subject to any requirement for such Personal Information or sensitive personal data or information to be retained by law or for legitimate business purposes.</li>
                            <li style={ { listStyle: "none" } }>(ii) We ask to each individual User(s) to identify themselves and the information requested to be accessed, corrected or removed before processing such requests, and we may decline to process requests that are unreasonably repetitive or systematic, require disproportionate technical effort, jeopardize the privacy of others, or would be extremely impractical (for instance, requests concerning information residing on backup tapes), or for which access is not otherwise required.</li>
                            <br />
                            <li style={ { listStyle: "none" } }>(iii) In any case where we provide information access and correction, we perform this service free of charge, except if doing so would require a disproportionate effort. (iv) Upon receiving a specific request coming from any of the User(s), we may ensure that Personal Information in relation to such User(s) is deleted from our database as also from the third-party cloud service providers.</li>
                            <li style={ { listStyle: "none" } }>(iv) Because of the way we maintain certain services, after you request for deletion of your Personal Information, residual copies may take a period of time before they are deleted from our active servers and may remain in our backup systems for a certain period of time.</li>
                        </Stack>
                        <Stack>
                            <Typography py={ 2 } sx={ { textTransform: "uppercase", fontWeight: "bolder" } }>11.Our Policies Concerning Children</Typography>
                            <li style={ { listStyle: "none" } }>We do not knowingly collect or solicit personal data from anyone under the age of 16 or knowingly allow such persons to use our Services. If you are under 16, please do not send any information about yourself to us, including your name, address, telephone number, or email address. No one under the age of 16 may provide any personal data. In the event that we learn that we have collected personal data from a child under age 16, we will delete that information as quickly as possible. If you believe that we might have any information from or about a child under the age of 16, please contact us.</li>
                        </Stack>
                        <Stack>
                            <Typography py={ 2 } sx={ { textTransform: "uppercase", fontWeight: "bolder" } }>12.grievance redressal mechanism</Typography>
                            <li style={ { listStyle: "none" } }>User(s) and/or any other person, whosoever has any grievances of any kind, are requested to click upon the direct link as provided herein below, for necessary action:</li>
                            <li style={ { listStyle: "none" } }><Link to="/contact" style={ { textDecoration: "none" } }>contact us</Link> We will be happy to provide any other necessary clarification in regard to this Privacy Policy or may help you to understand the implications of the same. Further, we may also help you in providing other information, at your request, with respect to our operations, as may be deemed reasonable by us. For the said purpose, you may reach out to the above-mentioned email address/postal address. The said request may take some time to be processed.</li>

                        </Stack>
                    </CardContent>
                </Card>
            </Container >
        </div >
    )
}

export default Privcypolicy
