import React from 'react'
import { Container, Card, CardContent, Typography, Stack } from "@mui/material"
import { Link } from "react-router-dom"

const Term = () => {
    return (
        <div style={ { minHeight: "100vh", padding: "2rem 0" } }>
            <Container maxWidth="lg">
                <Card style={ { minHeight: "100vh", boxShadow: "rgba(0, 0, 0, 0.1) 0px 14px 28px, rgba(0, 0, 0, 0.22) 0px 10px 10px" } }>
                    <Typography pt={ 2 } variant="h4" sx={ { textAlign: "center", fontWeight: "600", textTransform: "capitalize", letterSpacing: "1px" } }>terms and conditions</Typography>
                    <CardContent sx={ { padding: "2rem" } }>
                        <Stack>
                            <Typography py={ 1 } sx={ { color: "#063970", textTransform: "capitalize", fontWeight: "bold" } }>Welcome to Parthtech Developers LLP ("PARTH" or "Parthtech" or "Company" or "We").</Typography>
                            <Typography py={ 1 } sx={ { color: "#063970", textTransform: "capitalize", fontWeight: "bold" } }>We're a software development firm based in Gurugram, Haryana (India).</Typography>
                        </Stack>
                        <Stack>
                            <Typography py={ 2 } sx={ { textTransform: "uppercase", fontWeight: "bolder" } }>1.definations</Typography>
                            <p >(i)"Act": It means and include any of the following (as applicable)</p>
                            <p >(a)'The Information and Technology Act, 2000';</p>
                            <p >(b)'The Information and Technology (Amendment) Act, 2008';</p>
                            <p >(c)'The Consumer Protection Act, 2019'.</p>
                            <p >(ii)"Rule": It means and include any of the following (as applicable):</p>
                            <p >(a)The Information Technology (Reasonable Security Practices And Procedures And Sensitive Personal Data or Information) Rules, 2011; or</p>
                            <p >(a)The Information Technology (Reasonable Security Practices And Procedures And Sensitive Personal Data or Information) Rules, 2011; or</p>
                            <p >(iii)"Parthtech": It shall mean and include Parthtech Developers LLP, its partners, employees, affiliates, key managerial personnel etc.</p>
                            <p >(iv)"Company": It shall mean and include Parthtech Developers LLP, its partners, employees, affiliates, key managerial personnel etc.</p>
                            <p >(iv)"Company": It shall mean and include Parthtech Developers LLP, its partners, employees, affiliates, key managerial personnel etc.</p>
                            <p >(vi)"Website(s)/Mobile Application(s)": It shall mean and include all websites and mobile applications available for the User(s) owned and managed (directly or indirectly) by Parthtech Developers LLP.</p>
                            <p >(vii)"Service(s)": It means and include the various services offered by Parthtech to all its User(s) through the Website(s)/Mobile Application(s) of PARTH.</p>
                            <p >(viii) "User(s)": It shall mean and include all potential users, subscribers, consumers, registered or unregistered, natural or legal person, who access, subscribe or register to our Website(s)/Mobile Application(s) of PARTH.</p>
                            <p >(viii) "User(s)": It shall mean and include all potential users, subscribers, consumers, registered or unregistered, natural or legal person, who access, subscribe or register to our Website(s)/Mobile Application(s) of PARTH.</p>
                            <p >(x)"Public Forum": It means and include a chat portal for the users etc. to post or upload comments, feedback, data, links, videos, audios, graphics, images, messages and other material available in certain sections or pages of the Website(s)/Mobile Application(s) of PARTH.</p>
                            <p >(xi)"User(s) Content": It means and includes all or any comments, feedback, data, links, videos, audios, graphics, images, messages and any other materials uploaded by the Users of the said Website(s)/Mobile Application(s) of PARTH</p>
                            <p >(xii)"Terms of Use": It shall mean and include all terms and conditions incorporated into this agreement including any updates, modification done from time to time, and published in our Website(s)/Mobile Application(s) of PARTH.</p>
                            <p >(xiii)"Privacy Policy": It shall mean and include all terms and conditions incorporated into a document published and available in our Website(s)/Mobile Application(s) of PARTH under the heading called as 'Privacy Policy'.</p>
                            <p >(xiv)"User(s) Agreement": It refers to mean and include both documents i.e. the Terms of Use and the Privacy Policy, as published in our Website(s)/Mobile Application(s) of PARTH.</p>
                        </Stack>
                        <Stack>
                            <Typography py={ 2 } sx={ { textTransform: "uppercase", fontWeight: "bolder" } }>2.introduction</Typography>
                            <p >This user agreement ("Terms of Use") is an electronic record in terms of Information Technology Act, 2000 ("Act") and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology (Amendment) Act, 2008. This Terms of Use is generated by a computer system and does not require any physical or digital signatures.</p>
                            <p >This Terms of Use govern your use of our Website(s)/Mobile Application(s) of PARTH, Materials, Our Content and the services offered by PARTH upon the said Website(s)/Mobile Application(s) ("Service(s)").</p>
                            <p >For the purpose of this Terms of Use, wherever the context so require, User(s) shall mean any natural or legal person who has agreed to become a member of our Website(s)/Mobile Application(s) of PARTH by voluntarily registering on it as a registered user or otherwise browses/visits our Website(s)/Mobile Application(s) of PARTH without taking registration or subscription of any kind as available during the relevant time. Your access or use of the said Website(s)/Mobile Application(s) is subject to the terms and conditions of use as set out herein under this Terms of Use and the Privacy Policy made available at our Website(s)/Mobile Application(s) of PARTH.</p>
                            <p >Please note that by accessing or using the said Website(s)/Mobile Application(s), the User(s) voluntarily agree to be bound by this Terms of Use and, this Terms of Use is a legally binding agreement between the User(s) and Parthtech.</p>
                        </Stack>
                        <Stack>
                            <Typography py={ 2 } sx={ { textTransform: "uppercase", fontWeight: "bolder" } }>3.User(s) registration
                            </Typography>
                            <p >User(s) may use our Website(s)/Mobile Application(s) of PARTH without registration. However, in order to personalize your experience with PARTH, User(s) may create an account or you can login through your Google account or Mobile Number, as per the functionality made available on our Website(s)/Mobile Application(s) of PARTH during the relevant time.</p>
                            <p >User(s) further undertake and agree to:</p>
                            <p >a) provide true, accurate, correct and complete information as prompted by the applicable registration form made available at our Website(s)/Mobile Application(s) of PARTH;</p>
                            <p >b) provide true, accurate, correct and complete information as prompted by the applicable registration form made available at our Website(s)/Mobile Application(s) of PARTH;</p>
                            <p >You may be required to choose a password and user name. You are solely responsible for maintaining the confidentiality of your password/user name and the created account.</p>
                            <p >If at any time, Parthtech believe that in case the account and password of any User(s) is being misused in any manner, or that the information provided by such User(s) during the registration process is not true, inaccurate or incomplete, then Parthtech reserves the right to cancel your account and block your access to all platforms of our Website(s)/Mobile Application(s) of PARTH.</p>
                            <p >User(s) are entirely responsible for any and all activities that occur under their account. User(s) also agree to notify with us regarding any prior use or any unauthorized use of their account or any breach of security. Further, We shall not be liable for any loss of User(s) that may incur as a result of someone else using its password or account or User(s) itself failure to comply with this section.</p>

                        </Stack>
                        <Stack>
                            <Typography py={ 2 } sx={ { textTransform: "uppercase", fontWeight: "bolder" } }>4. use of website(s)/ mobile application(s) of path</Typography>
                            <p >Materials provided on our Website(s)/Mobile Application(s) of PARTH, including but not limited to all information, materials, functions, texts, logos, designs, graphics, images, sounds, software, documents, products and services ("Materials"), and the selection, arrangement and display thereof, may be the copyrighted works of Parthtech or its vendors or third party service providers. All Materials herein and all software are owned by Parthtech/its partners and protected by worldwide copyright and other intellectual property laws as applicable. Except as stated herein, none of the Materials may be modified, copied, reproduced, distributed, republished, downloaded, displayed, sold, compiled, posted or transmitted in any form or by any means, including but not limited to, electronic, mechanical, photocopying, recording or other means, without the prior express written permission of Parthtech.</p>
                            <p >We hereby grant all our User(s) the right to access and use our Website(s)/Mobile Application(s) of PARTH only for their personal and non-commercial use. User(s) may not use it for commercial purposes or in any way that is unlawful, or harms us or any other person or entity, as determined in our sole discretion.</p>
                            <p >User(s) may post or share any links, images, texts and/or contents from our Website(s)/Mobile Application(s) of PARTH to social platforms like Facebook, Twitter, Google+, Whatsapp, etc., with appropriate link-back to the original source.</p>
                            <p >Our Website(s)/Mobile Application(s) of PARTH including the Materials are made available for public use in general and for non-commercial usage only. The intellectual property (if any) available in our Website(s)/Mobile Application(s) of PARTH, including the Materials, are solely owned by Parthtech/its partners.</p>
                            <p >In respect of the contents available within our Website(s)/Mobile Application(s) of PARTH, including the Materials, all User(s) have to:</p>
                            <p >(a) Keep intact all copyright and other proprietary notices;</p>
                            <p >(b) Make no modifications to, and do not rent, lease, loan, sell, distribute, copy or create any derivative works based upon the work of Parthtech or the Materials created/developed/ideated by Parthtech, in whole or in part;</p>
                            <p >(c) Not transfer any Materials or software or any part thereof to any other computer or mobile device;</p>
                            <p >(d) Restrain from any commercial or business use of PARTH or any Materials including the software etc. as the same is expressly prohibited by Parthtech; and</p>
                            <p >(e) Ensure that none of the all or any functionalities, features etc. available at our Website(s)/Mobile Application(s) of PARTH are replicated or reproduced by our User(s) or by any third person at any other different website, mobile application or any other platform.</p>
                            <p >Except as expressly provided above, nothing contained herein shall be construed as conferring, by implication, estoppel or otherwise, any license or right in respect of any patent, trademark or copyright of Parthtech upon any person.</p>
                            <p >User(s) acknowledge and agree that nothing in this Terms of Use shall have the effect of transferring the ownership of any copyrights, trademarks, service marks, trade names or any other proprietary rights available with our Website(s)/Mobile Application(s) of PARTH, other Materials or any part thereof to them or any other third party.</p>
                        </Stack>
                        <Stack>
                            <Typography py={ 2 } sx={ { textTransform: "uppercase", fontWeight: "bolder" } }>5. prohibited use</Typography>
                            <p >As a condition of use of our Website(s)/Mobile Application(s) of PARTH by the User(s), they will not use it for any purpose that is unlawful or prohibited by these Terms of Use or by any domestic or international laws, statutes, ordinances and regulations. It is clarified that the use of our Website(s)/Mobile Application(s) of PARTH by the User(s) is the sole responsibility of the User(s) itself only.</p>
                            <p >You shall not display, upload, modify, publish, transmit, update or share any information into our Website(s)/Mobile Application(s) of PARTH, that –</p>
                            <p >You shall not display, upload, modify, publish, transmit, update or share any information into our Website(s)/Mobile Application(s) of PARTH, that –</p>
                            <p >a) belongs to another person and to which you do not have any right;</p>
                            <p >b) is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, pedophilic, libelous, invasive of another&#39;s privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner;</p>
                            <p >c) involves the transmission of "junk mail", "chain letters", "unsolicited mass mailing", "spamming" or "unsolicited commercial advertisement";</p>
                            <p >d) harm minors in any way;</p>
                            <p >e) infringes any patent, trademark, copyright or other proprietary rights;</p>
                            <p >f) violates any law for the time being in force;</p>
                            <p >g) deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;</p>
                            <p >h) impersonate another person;</p>
                            <p >i) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of our resources/contents in general;</p>
                        </Stack>
                        <Stack>
                            <Typography py={ 2 } sx={ { textTransform: "uppercase", fontWeight: "bolder" } }>6. use of public form</Typography>
                            <p >Certain sections or pages of the Website(s)/Mobile Application(s) of PARTH may contain a provision such as chat portal for users etc. (hereinafter referred to as the "Public Forum") for the users to post or upload comments, feedback, data, links, videos, audios, graphics, images, messages and other material ("User Content"). Through the Public Forum, any User(s) can communicate with our other users of the Website(s)/Mobile Application(s) of PARTH.</p>
                            <p >User(s) are solely and entirely responsible regarding all their User Content that they upload, post, email, transmit or otherwise make available the same upon the Public Forum. User(s) fully understand and acknowledge that such User Content can be viewed by other users globally and therefore User(s) shall exercise due care to ensure that such User Content does not offend or abuse other users of our Website(s)/Mobile Application(s) of PARTH.</p>
                            <p >Parthtech does not control the User Content posted on the Public Forum and, as such, does not guarantee the accuracy, integrity or quality of such User Content. User(s) understand that by using our Website(s)/Mobile Application(s) of PARTH, they may be exposed to User Content that is offensive, indecent or objectionable.</p>
                            <p >Under no circumstances, Parthtech will be liable in any way for any User Content, including, but not limited to, for any errors or omissions in any User Content, or for any loss or damage of any kind incurred as a result of the use of any User Content posted, emailed, transmitted or otherwise made available on our Website(s)/Mobile Application(s) of PARTH.</p>
                            <p >When our User(s) post or upload their User Content on our Website(s)/Mobile Application(s), they grant Parthtech (and its licensees, distributors, agents, representatives and other authorized persons) the irrevocable rights in perpetual, royalty-free, non-exclusive and a license to reproduce, prepare derivative works based upon such User Content, and to distribute, perform or display such User Content, in whole or in part, in any form, on any media or technology known or hereafter developed.</p>
                            <p >User Content posted by our User(s) shall be subject to the relevant laws and may be disabled, or/and may be subject to investigation under the appropriate laws. User(s) agree that Parthtech may disclose or preserve User Content if required to do so by law or in the good faith belief that such preservation or disclosure is reasonably necessary to:</p>
                            <p >(a) comply with legal process;</p>
                            <p >(b) respond to claims that any User Content violates the rights of third-parties; or</p>
                            <p >(c) protect the rights, property, or personal safety of Parthtech and the public.</p>
                            <p >Furthermore, if any User(s) are found to be in non-compliance with the laws and regulations, these Terms of Use, or the Privacy Policy of our Website(s)/Mobile Application(s) of PARTH, Parthtech may terminate his/her account/block the access and, also further reserve the right to remove any of such User Content that is non-compliant with our policies in general.</p>
                            <p >User(s) agree that Parthtech has no liability or responsibility for the storage or deletion of any User Content and reserves the right to change its general practices and limits at any time in its sole discretion, with or without notice to its User(s).</p>
                        </Stack>
                        <Stack>
                            <Typography py={ 2 } sx={ { textTransform: "uppercase", fontWeight: "bolder" } }>7.copyright and trademarks</Typography>
                            <p >Unless otherwise stated, copyright and all intellectual property rights in all Materials on our Website(s)/Mobile Application(s) of PARTH [including but not limited to text, audio, video or graphical images, or technology, the look and feel of the website/mobile application, trademarks and logos appearing on our Website(s)/Mobile Application(s) of PARTH] may be the property of Parthtech and may be owned and controlled by us or by other parties that have licensed their material to us. Materials on our Website(s)/Mobile Application(s) are solely for your personal, non-commercial use. Some content used on our Website(s)/Mobile Application(s) of PARTH may be taken from public domain and displayed herein. User(s) are bound to respect the respective intellectual property rights that may subsist in such Materials made available on our Website(s)/Mobile Application(s). User(s) must not copy, reproduce, republish, upload, post, transmit or distribute the Materials in any way, including by e-mail or other electronic means and whether directly or indirectly and must not assist any other person to do so. Without the prior written consent of the owner, modification of the Materials, use of the Materials on any other web site or networked computer environment or use of the Materials for any purpose other than personal, non-commercial use is a violation of the copyrights, trademarks and other proprietary rights, and is strictly prohibited. Any use for which the User(s) receive any remuneration, whether in money or otherwise, is a commercial use for the purposes of this clause. User(s) agree not to use any framing techniques to enclose any trademark or logo or other proprietary information of Parthtech/PARTH or remove, conceal or obliterate any copyright or other proprietary notice or any credit-line or date-line on other mark or source identifier included on our Website(s)/Mobile Application(s) of PARTH, including without limitation, the size, colour, location or style of all proprietary marks. Any infringement shall be vigorously defended and pursued to the fullest extent as permitted by the appropriate laws.</p>
                            <p >We respect other people&#39;s intellectual property rights and if you believe that any content or material on our Website(s)/Mobile Application(s) of PARTH infringes on your intellectual property rights, the User(s) or any other concerned person are requested to click upon <Link to="\contact">contact us</Link> in order to know further details for necessary action.</p>
                        </Stack>
                        <Stack>
                            <Typography py={ 2 } sx={ { textTransform: "uppercase", fontWeight: "bolder" } }>8.links</Typography>
                            <p >We may establish, on our Website(s)/Mobile Application(s) of PARTH, a hypertext link(s) to a third party website from time to time. Such link(s) are provided for information and convenience for our User(s) and does not state or imply any sponsorship or endorsement of third party website. Parthtech has no control over such third party website and use of such third party website or any offsite dealings with such third parties by User(s) is at their own risk and responsibility.</p>
                        </Stack>
                        <Stack>
                            <Typography py={ 2 } sx={ { textTransform: "uppercase", fontWeight: "bolder" } }>9.use of google anyaltics</Typography>
                            <p >Our Website(s)/Mobile Application(s) of PARTH use Google Analytics, a web analytics service provided by Google, Inc. ("Google"). Google Analytics uses "cookies", which are text files placed on your computer, to help the website analyze how User(s) use the website or mobile application. The information generated by the cookie about your use of the website/mobile application (including your IP address) will be transmitted to and stored by Google on servers in the United States. Google will use this information for the purpose of evaluating your use of the website or mobile application, compiling reports on website activity for website operators and providing other services relating to website activity and Internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google&#39;s behalf. By using this website/mobile application, User(s) consent to the processing of data about you by Google in the manner and for the purposes set out above.</p>
                        </Stack>
                        <Stack>
                            <Typography py={ 2 } sx={ { textTransform: "uppercase", fontWeight: "bolder" } }>10.advertising material</Typography>
                            <p >Some part or portion of our Website(s)/Mobile Application(s) of PARTH may contain advertising information or promotion material or other material submitted to us by third parties.</p>
                            <p >Responsibility for ensuring that the material submitted for inclusion on our Website(s)/Mobile Application(s) of PARTH complies with applicable laws is exclusively on the party providing the information/material. User(s) correspondence or business dealings with, or participation in promotions of advertisers or including payment and delivery of related goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between the User(s) and such advertiser. We will not be responsible or liable for any claim, error, omission, inaccuracy in advertising material or any loss or damage of any sort incurred as the result of any such dealings or as the result of the presence of such advertisers on our Website(s)/Mobile Application(s) of PARTH. We reserve the right to omit, suspend or change the position of any advertising material submitted for insertion.</p>
                            <p >We do not guarantee or give any kind of assurance to all or any of the User(s) doing anything in furtherance to or relying upon such advertising materials of third party advertisers.</p>
                            <p >It is expressly clarified that any sponsored content of any goods/service/activity (expressly displayed at respective portions on our Website(s)/Mobile Application(s) of PARTH) displayed are not solicited by Parthtech and it should not be deemed as a promotion made at the behest of Parthtech.</p>
                        </Stack>
                        <Stack>
                            <Typography py={ 2 } sx={ { textTransform: "uppercase", fontWeight: "bolder" } } >11.international use</Typography>
                            <p >Parthtech is a company incorporated as per the laws applicable in India and it makes no representation that our Website(s)/Mobile Application(s) of PARTH is appropriate or available in locations outside of India. Those who choose to access it from other locations do so at their own risk and are solely responsible for compliance with applicable laws.</p>
                        </Stack>
                        <Stack>
                            <Typography py={ 2 } sx={ { textTransform: "uppercase", fontWeight: "bolder" } }>12.disclaimer and limitation of liability</Typography>
                            <p >(a) By accessing and/or using our Website(s)/Mobile Application(s) of PARTH and its service (hereinafter referred to as the "Service"), User(s) have read, understood and agree to be legally bound by the terms of this disclaimer. User(s) agree that your access to the Service is at your sole risk and at your free will.</p>
                            <p >(b) The Service and all material therein contained are distributed and transmitted on an "as is" and "as available" basis.</p>
                            <p >(c) We disclaim any and all express or implied representations, warranties and/or conditions of any kind, including but not limited to warranties of completeness, accuracy, reliability, suitability, fitness, merchantability, availability, quality, fitness for any purpose, non- infringement, compatibility and/or security;</p>
                            <p >(d) We are not responsible or liable for any infection or contamination of your system or device arising out of or in connection with your use of the Service or any connected service and do not warrant that the Service, the server(s) that make the Service available or any connected services are free from viruses, trojan horses, worms, software bombs or similar items or processes or other harmful components;</p>
                            <p >(e) We are not responsible or liable for interruptions, delays, inaccuracies, errors, or omissions arising out of your use of the Service or any connected service or with respect to the material and user material thereon; and</p>
                            <p >(f) We do not warrant that the Service, or any connected service, linked microsites, any materials, third-party content, other services offered will be uninterrupted or error free or accurate or suit your purpose.</p>
                            <p >(g) Industry standard efforts are made to keep the Service running smoothly. However, Parthtech takes no responsibility for, and will not be liable for, the Service being unavailable due to any reasons.</p>
                            <p >(h) The entire risk as to the quality, accuracy, adequacy, completeness, fitness, correctness and validity of any material and use of and access to the Service or any connected service rests solely with you.</p>
                            <p >(i) User(s) may encounter third party applications while using the Service including, without limitation, websites, widgets, software, services that interact with the service. Your/User(s) use of these third party applications shall be subject to such third party terms of use or license terms. Parthtech shall not be liable for any representations or warranties or obligations made by such third party applications to you under contract or law.</p>
                            <p >(j) The Service may contain links to other third-party websites/services which are not under the control of Parthtech. Any website/application you visit by a link from the Service is solely the responsibility of the third party providing the website. The content of, including materials and information contained on, any third-party website/application to which you link from the Service is solely the responsibility of the provider of that third party website/application. Any transactions that you enter into with a third party listed in this Service or linked from this Service are solely between you and that third party. We are not responsible for any such third-party content/feature that may be accessed via the Service, nor the organizations publishing those third-party websites/applications, and hereby disclaim any responsibility and liability for such content. The inclusion of any links does not constitute or imply an endorsement or recommendation by us of the third- party, of the quality of any product or service, advice, information or other materials displayed, purchased, or obtained by you as a result of an advertisement/functionality/necessary embedment or integrations, any other information or offer in or in connection with the third party website/application.</p>
                            <p >(k) To the fullest extent permissible by law, Parthtech, its affiliates, associates and group companies, and their respective directors, key managerial personnel, employees, officers, shareholders/partners, agents, representatives, sub-contractors, consultants and third- party providers shall not be liable for any loss and/or damage and/or claims of any kind (whether in contract, tort or breach of statutory duty or otherwise) arising out of or in connection with the Service and/or materials and/or user material and/or any connected third party website including without limitation:</p>
                            <p >(i) Indirect or consequential loss;</p>
                            <p >(ii) Loss of profits or revenue or savings or other economic loss;</p>
                            <p >(iii) Incidental, direct, or special loss or similar damages;</p>
                            <p >(iii) Incidental, direct, or special loss or similar damages;</p>
                            <p >(v) Loss of business, reputation or goodwill;</p>
                            <p >(vi) Loss of use;</p>
                            <p >(vii) Wasted or lost management time;</p>
                            <p >(viii) Even if advised of the possibility of such loss or damage or if such loss or damage was foreseeable.</p>
                            <p >(l) When the User(s) share password or allow a third party to access his/her account, he/she agrees to remain responsible for compliance with this Terms of Use by any such third party. We will not be liable for any loss or damage arising from your failure to adequately safeguard your password or for any actions occurring under your password.</p>
                            <p >(m) User(s) agree that Parthtech shall not be liable for any direct, special, incidental, indirect or consequential damages of any kind in connection with this agreement or your use of our Website(s)/Mobile Application(s) of PARTH, even if Parthtech has been informed in advance of the possibility of such damages.</p>
                            <p >(n) Notwithstanding the foregoing, in no event shall Parthtech or its affiliates, associates and group companies&#39; liability to you for any and all losses, damages or claims of whatsoever nature (whether in contract, tort, breach of statutory duty or otherwise) including under the Privacy Policy shall exceed the amount paid by you, if any, for accessing the Service provided. However, the maximum liability, in any case, whatsoever, of Parthtech in all instances shall not exceed INR 500 (Indian National Rupees Five Hundred only).</p>
                            <p >(o) If you are dissatisfied with the Service or with these Terms of Use or the Privacy Policy of our Website(s)/Mobile Application(s) of PARTH, your sole and exclusive remedy is to discontinue accessing or using the Service.</p>
                        </Stack>
                        <Stack>
                            <Typography py={ 2 } sx={ { textTransform: "uppercase", fontWeight: "bolder" } }>13.idemnity</Typography>
                            <p >User(s) agree to indemnify, defend and hold Company, its officers, directors, employees, affiliates or representatives harmless from any claim or action (including legal expenses) arising out of your use of our Website(s)/Mobile Application(s) of PARTH, your breach of the Terms of Use, Privacy Policy and violation of any third party intellectual property rights or privacy in any way.</p>
                        </Stack>
                        <Stack>
                            <Typography py={ 2 } sx={ { textTransform: "uppercase", fontWeight: "bolder" } }>14.changes of term of use</Typography>
                            <p >We reserve our right to modify these Terms of Use and the Privacy Policy at any time, at our sole discretion. Any changes to Terms of Use or the Privacy Policy will be posted on our Website(s)/Mobile Application(s) of PARTH and your continued use of the same following a posting of such change is your agreement to all such changes made &amp; updated and, all User(s) are bound by the then-current version of these Terms of Use or the Privacy Policy inserted upon our Website(s)/Mobile Application(s) of PARTH. If any changes to these Terms of Use or the Privacy Policy are unacceptable to you, you must discontinue using our Website(s)/Mobile Application(s) of PARTH. We reserve the right to suspend or deny, in our sole discretion, your access to all or any portion of our Website(s)/Mobile Application(s) of PARTH, including for any violation of any provision of these Terms of Use and/or the Privacy Policy. We also reserve the right to change our Website(s)/Mobile Application(s) of PARTH without any prior notice to the User(s), at any time.</p>
                        </Stack>
                        <Stack>
                            <Typography py={ 2 } sx={ { textTransform: "uppercase", fontWeight: "bolder" } }>15.relationship</Typography>
                            <p >None of the provisions of the Terms of Use and the Privacy Policy shall be deemed to constitute a partnership or agency between the User(s) and Parthtech and, User(s) shall have no authority to bind Parthtech in any manner, whatsoever. If the User(s) are registering on our Website(s)/Mobile Application(s) of PARTH as a business entity, you represent that you have the authority to bind your entity with all terms of this Terms of Use and the Privacy Policy of our Website(s)/Mobile Application(s) of PARTH.</p>
                        </Stack>
                        <Stack>
                            <Typography py={ 2 } sx={ { textTransform: "uppercase", fontWeight: "bolder" } }>16.termination</Typography>
                            <p >We reserve the right, at our discretion, to immediately, with or without notice, suspend or terminate your registration/subscription, the Terms of Use, and/or your access to all or a portion of our Website(s)/Mobile Application(s) of PARTH and/or remove any registration information or User Content from our Website(s)/Mobile Application(s) of PARTH, for any reason. Upon termination or expiration of the Terms of Use or of your registration/subscription, your obligations and Parthtech's rights and disclaimers survive, but your right to use our Website(s)/Mobile Application(s) of PARTH immediately ceases. Any express waiver or failure to exercise promptly any right under the Terms of Use will not create a continuing waiver or any expectation of non-enforcement.</p>
                        </Stack>
                        <Stack>
                            <Typography py={ 2 } sx={ { textTransform: "uppercase", fontWeight: "bolder" } }>17. miscellaneous</Typography>
                            <p >(a) These Terms of Use contain the entire understanding between User(s) and Parthtech and supersedes all prior understanding between the User(s) and Parthtech in respect of the User(s)&#39;s access and/or use of the Service.</p>
                            <p >(b) If any provision of these Terms of Use is found to be illegal, invalid or unenforceable, then to the extent to which such provision is illegal, invalid or otherwise unenforceable, it shall be severed and deleted and the remaining provisions shall survive and remain in full force and effect and continue to be binding and enforceable.</p>
                            <p >(c) User(s) confirm that their representations, warranties, undertakings and covenants, and the clauses relating to indemnities, limitation of liability, grant of license, governing law, confidentiality shall survive the efflux of time and the termination of these Terms of Use and the Privacy Policy of our Website(s)/Mobile Application(s) of PARTH.</p>
                            <p >(d) Any express waiver or failure to exercise promptly any right under these Terms of Use and the Privacy Policy of our Website(s)/Mobile Application(s) of PARTH will not create a continuing waiver or any expectation of non-enforcement.</p>
                            <p >(e) User(s) agree that Parthtech shall be under no liability whatsoever to its User(s) in the event of non-availability of the Service or any portion thereof occasioned by Act of God, pandemic, war, disease, revolution, riot, civil commotion, strike, lockout, flood, fire, satellite failure, network failures, server failures, failure of any public utility, terrorist attack, network maintenance, service maintenance, server maintenance, or any other cause whatsoever beyond the control of Parthtech.</p>
                            <p >(f) Unless otherwise specified, the Service is presented solely for the purpose of entertainment and promoting programs. Parthtech makes no representation that the Service is appropriate or available for use in locations other than India. Those who choose to access the Service from locations other than in India, do so on their own initiative and risk, and are solely responsible for compliance with the relevant applicable local laws.</p>
                            <p >(g) The Privacy Policy (as also provided in our Website(s)/Mobile Application(s) of PARTH), and any other documents, instructions, etc. included on our Website(s)/Mobile Application(s) of PARTH shall be read into this and shall be a part of these Terms of Use. The Privacy Policy shall form an integral part of the Terms of Use and both these documents constitute the User(s) Agreement and a legally binding contract between Parthtech and the User(s).</p>
                            <p >(h) These Terms of Use shall be governed by and construed in accordance with the laws of the India and be subject to the exclusive jurisdiction of the Courts at Delhi (India), without giving effect to any principles of conflicts of law.</p>
                        </Stack>
                    </CardContent>
                </Card>
            </Container>
        </div >
    )
}

export default Term
